# Generated by Django 4.2.16 on 2024-09-07 19:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos.', regex='^\\d{11}$')], verbose_name='CPF')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço Completo')),
                ('funcao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Função/Cargo')),
                ('salario', models.DecimalField(decimal_places=2, default=1430, max_digits=8, null=True, verbose_name='Salário R$')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'ordering': ['nome', 'cpf', 'celular'],
            },
        ),
        migrations.CreateModel(
            name='medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('crm', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999999)], verbose_name='CRM')),
                ('crm_uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], default='GO', max_length=2, verbose_name='CRM UF')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('funcao', models.CharField(blank=True, max_length=30, null=True, verbose_name='Função')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 dígitos.', regex='^\\d{11}$')], verbose_name='CPF')),
                ('email', models.CharField(max_length=50, verbose_name='E-mail')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome do Procedimento')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do Procedimento')),
                ('paciente', models.CharField(max_length=50, verbose_name='Nome do Paciente')),
                ('medico', models.CharField(max_length=50, verbose_name='Nome do Médico')),
            ],
        ),
    ]
