# Generated by Django 4.2.16 on 2024-09-08 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento',
            options={'ordering': ['nome']},
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='data',
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='procedimento',
            name='paciente',
        ),
        migrations.AddField(
            model_name='procedimento',
            name='cid',
            field=models.CharField(default=None, max_length=20, verbose_name='CID'),
        ),
        migrations.AddField(
            model_name='procedimento',
            name='valor',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='procedimento_executado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True, verbose_name='Data do Procedimento')),
                ('obs', models.CharField(max_length=50, verbose_name='Obs')),
                ('quantidade', models.FloatField(blank=True, default=None, null=True, verbose_name='Quantidade')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.paciente')),
                ('procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.procedimento')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
