# Generated by Django 4.2.16 on 2024-09-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_alter_procedimento_options_remove_procedimento_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento_executado',
            options={'ordering': ['data', 'paciente']},
        ),
        migrations.AlterField(
            model_name='procedimento_executado',
            name='obs',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Observação'),
        ),
    ]
