# Generated by Django 4.2.16 on 2024-09-09 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_alter_procedimento_executado_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='procedimento_executado',
            options={'ordering': ['-data', 'paciente']},
        ),
    ]
